### ISSUE TITLE
Is the multinode data processing only available in lightning studio?

### ISSUE THREAD

**Issue by rishabhm12** [Lightning-AI/litdata#218]
Is the multinode data processing only available in lightning studio?
The optimize() dataset function takes in two params num_nodes and machine, we cannot use this outside the studio env like databricks etc? If not, can we have it working for other envs?

**Comment by tchaton** [comment]
Hey @rishabhm12.

Right now, it is only supported on Lightning AI. There is more to it than env variables.

Best,
T.C

**Comment by tchaton** [comment]
Hey @rishabhm12,

What's your use case ?

Best,
T.C

**Comment by ethanhe42** [comment]
can I use multinode data processing in slurm?

**Comment by tchaton** [comment]
Hey @ethanhe42, Yes, you can.

**Comment by ethanhe42** [comment]
It says lightning studio only. Do you have an example for slurm? I have standard pytorch ddp env variable

**Comment by tchaton** [comment]
Nice. Do you use it a lot ? Any feedbacks ?

**Comment by Bizilizi** [comment]
There are two things I found unexpected while working with litdata:

**1. HF datasets protocol and revision support**
The HF datasets protocol doesn’t seem to be fully supported, specifically revisions.

For example, links like

```python
minhuh/prh@wit_1024
```
work fine with methods such as `index_hf_dataset`, since those call into the Hugging Face library directly (see [parquet.py#L246](https://github.com/Lightning-AI/litData/blob/76d3bee8e0aaa925941c47f35c7784a46d08afe5/src/litdata/utilities/parquet.py#L246)), which eventually invokes resolve_path from HF.

However, when the same link goes through your `HFDownloader`, it gets parsed by [downloader.py#L526](https://github.com/Lightning-AI/litData/blob/76d3bee8e0aaa925941c47f35c7784a46d08afe5/src/litdata/streaming/downloader.py#L526):

```python
_, _, _, repo_org, repo_name, path = remote_filepath.split("/", 5)
repo_id = f"{repo_org}/{repo_name}"
downloaded_path = hf_hub_download(
    repo_id,
    path,
    cache_dir=tmpdir,
    repo_type="dataset",
    **self._storage_options,
)
```
At this point repo_name becomes `minhuh/prh@wit_1024`, which is invalid.
A more robust approach would be to let `HfFileSystem` resolve the path:
```python
fs = HfFileSystem()
hf_resolved_path = fs.resolve_path(remote_filepath)

downloaded_path = hf_hub_download(
    hf_resolved_path.repo_id,
    hf_resolved_path.path_in_repo,
    revision=hf_resolved_path.revision,
    cache_dir=tmpdir,
    repo_type=hf_resolved_path.repo_type,
    **self._storage_options,
)
```
This way revisions are handled correctly. Alternatively, and perhaps even clear solution is to handle it with `storage_options` argument, but currently its not going all the way through to `**self._storage_options,`, so, effectively, they are ignored. 

---

**2. batch_size behavior in optimize**
The current behavior of the `optimize(..., batch_size=...)` function is a bit surprising.

Right now, inputs are batched and stored as batches. This becomes tricky in large-scale embedding scenarios (e.g. millions of images/texts distributed across workers with GPUs). You naturally want to batch inputs for efficiency, but then you end up with chunks where each element is itself already a batch of embeddings.

Later, if you load the data with a StreamingDataLoader, you effectively get double batching:
```python
dataset = ld.StreamingDataset(args.input_dir, shuffle=True, drop_last=True)
dataloader = ld.StreamingDataLoader(dataset, batch_size=4)
```
This means you have to flatten the stored batches first if your training batch size differs from the optimize batch size.

It might be worth considering:
- Adding an option in optimize to automatically flatten batches before storing, or
- Making flattening the default behavior (since training/evaluation often uses different batch sizes than preprocessing).

Let me know you think those features make sense. I can try to find some time in the upcomming weeks to contribute.

**Comment by tchaton** [comment]
For 2. You can use yielding. So you process a batch but yield eac sample indivifually.
